services:
  wcs-app:
    build: .
    container_name: wcs-app
    ports:
      - "8080:8080"
    environment:
      - SERVER_ADDR=:8080
      - DB_URL=postgres://user:password@db:5432/serviceDb
      - ADMIN_TOKEN=87655967-9af5-40d3-8cd4-051083213800
      - LOCAL_STORAGE_PATH=./LocalFilesStorage
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    container_name: service_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: serviceDb
    ports:
      - "5433:5432"
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d service_db"]
      interval: 5s
      timeout: 5s
      retries: 10